### ISSUE TITLE
测试失败

### ISSUE THREAD

**Issue by ghost** [letssudormrf/ss-obfs-docker#1]
docker run --restart always -d -p 443:8443/tcp -p 443:8443/udp --name simple-obfs -e OPTS="-s 0.0.0.0 -p SSport -m aes-256-cfb -k SSPasswd --plugin obfs-server --plugin-opts obfs=tls;failover=www.bing.com:443"  letssudormrf/ss-obfs-docker

 客户端接收不到数据，不混淆的情况下客户端数据接收正常

**Comment by ghost** [comment]
请问参数是不是有问题？

**Comment by letssudormrf** [comment]
@haohowey 

The args of Port number is incorrect. Please kindly check. 
> -e OPTS="-s 0.0.0.0 -p 8443 -m aes-256-cfb -k SSPasswd --plugin obfs-server --plugin-opts obfs=tls;failover=www.bing.com:443" letssudormrf/ss-obfs-docker

You should use the client which has the simple-obfs plugin,
because the failover option has been enabled, it means that the origin protocol doesn't work. 

Therefore,
the client without simple-obfs cannot work.
Only the client use simple-obfs can work.

**Comment by ghost** [comment]
docker run --restart always -d -p 443:8443/tcp -p 443:8443/udp --name simple-obfs -e OPTS="-s 0.0.0.0 -p 8443 -m aes-256-cfb -k SSPasswd --plugin obfs-server --plugin-opts obfs=tls" letssudormrf/ss-obfs-docker
以上命令run docker 还是不行，但是在client启动时能接收到几kb的数据，后面就断了
client使用的是google play上shadowsocks作者（max lv）提供的simple obfuscation插件，ss client也是由max lv提供，docker image也是由 www.shadowsocks.org官方提供

**Comment by letssudormrf** [comment]
@haohowey 

Maybe the simple-obfs was restricted by the ISP.

Let's change to v2ray, it's very easy to deploy.
Websocket + TLS can pass-through CDN. 

[](https://github.com/letssudormrf/v2ray-docker)

> docker run --restart always -d -p 80:8080/tcp -p 443:8443/udp --name v2ray-docker -e UUID="082c8ac4-d1df-4005-9d29-8417cc4a3940" -e WSPATH="/api/" letssudormrf/v2ray-docker

The android client has BifrostV.
